### ISSUE TITLE
Pornhub的问题

### ISSUE THREAD

**Issue by Alanomn** [684102/PornDownloader.user.js#2]
安装脚本后，导致网站右上角出现问题 https://cn.pornhub.com/

信息                ：  消失
好友申请  通知： 无法鼠标点击

没安装脚本前：
![ScreenShot00267](https://user-images.githubusercontent.com/12547795/79781431-0a439b00-8370-11ea-8755-d6f2d8b91a18.png)

安装脚本后：
![ScreenShot00268](https://user-images.githubusercontent.com/12547795/79781575-40811a80-8370-11ea-81a2-3ad17c1262c0.png)

**Comment by 684102** [comment]
问题已根本解决。
