### ISSUE TITLE
Download links are missing on PornHub

### ISSUE THREAD

**Issue by MacGnG** [684102/PornDownloader.user.js#3]
The pink download buttons show up for half a second and then disappear. Too fast to click. In the source of the webpage, the 1080P MP4 links are visible under the download section. THANKS.

Edit: I am on Version 20203045

**Comment by 684102** [comment]
Please check your another extension and make sure there are not conflict with Porn Downloader script.
I just checked on lastest version and no issue found on both pornhubpremium and pornhub.

**Comment by 684102** [comment]
i've updated to 20203055, you can please try again then tell me that issue is resolved or not. 
The script can be update at : https://bit.ly/porndown2

**Comment by MacGnG** [comment]
it is another extension. thanks.

**Comment by gluons** [comment]
It's blocked by this rule on EasyList (Adblock filter).

```
pornhub.com,pornhubthbh7ap3u.onion##.video-wrapper > #player + [class]
```

https://github.com/easylist/easylist/blob/d036d9ab2250256a5ab9be86b1938c5b989e475a/easylist_adult/adult_specific_hide.txt#L872

---

To solve this problem, add this rule into your custom rules.

```
pornhub.com#@#.video-wrapper > #player + [class]
```

**Comment by 684102** [comment]
> It's blocked by this rule on EasyList (Adblock filter).
> 
> ```
> pornhub.com,pornhubthbh7ap3u.onion##.video-wrapper > #player + [class]
> ```
> 
> https://github.com/easylist/easylist/blob/d036d9ab2250256a5ab9be86b1938c5b989e475a/easylist_adult/adult_specific_hide.txt#L872
> 
> To solve this problem, add this rule into your custom rules.
> 
> ```
> pornhub.com#@#.video-wrapper > #player + [class]
> ```

This issue was resolved. Thank you for your input and feedback. 
update to 20203060 now at https://bit.ly/porndown2
