### ISSUE TITLE
Forced upgrade script ads

### ISSUE THREAD

**Issue by Alanomn** [684102/PornDownloader.user.js#5]
Every time I open Pornhub, an ad prompting me to upgrade the script will appear. This script is just an ordinary upgrade, it is necessary to make me annoyed every time? And this script is updated frequently, I do n’t want to use it anymore ...

**Comment by 684102** [comment]
You just turn off the modal by click [X]
And it will remind you after next day.

today i have many fix  , that about new feature allowe you to hack premium video for free, that why you getting that alert modal.
ps. You can view the premium/prices video at pornhub for free now.
thx you for using my script
