### ISSUE TITLE
Requesting name addition to the link of the video

### ISSUE THREAD

**Issue by NightLancer** [684102/PornDownloader.user.js#6]
Hello! 
Nice script out there, but it may be even better! ;)

By default, all content in newly opened tabs are saved by the name of a content. For example, if you want to save video opened by your download button, the name of content during saving will be like "1080P_8000K_178052921.mp4". That is not very informative, to be true... When you want to compare list of your downloaded videos and currently placed on the site page, you have no comparable value for that purpose=\ (for example: on the site your see "oiled stretched belly", and in your folder you see " 1080P_4000K_154717332.mp4"). It is very uncomfortable... 

My proposition is to add title name to the source link. So, when you save the video from new tab - it can be used for the filename. 
 
The title name can be received by the  
`document.querySelectorAll('div.title-container > h1 > span')[0].textContent;`
![image](https://user-images.githubusercontent.com/19971564/82568375-607e4680-9b87-11ea-8283-c171b0619181.png)
You can add it to the end of href by `... += '&name=' + ...`

Current example of work in console: 
`document.querySelectorAll('.downloadBtn')[0].href += '&name=' + document.querySelectorAll('div.title-container > h1 > span')[0].textContent`
![image](https://user-images.githubusercontent.com/19971564/82568321-49d7ef80-9b87-11ea-8dbb-e1c0bd11bb21.png)

Some old(short?) videos are starting downloading immediately, so this feature will not work for them. But if it downloads so fast - you can rename it in brief moment of time. But in the case of ~300mb video and poor server upload speed - it may take a ten minutes to download... 
For such a case(and for all cases when PH/browser opens video in new tab, instead of downloading it) - name addition would be great feature.

Using simple code in video tab, you can download it without bother of subtracting it manually from the link. 
`
var anchor = document.createElement('a'); 
var h = anchor.href = document.querySelectorAll('video')[0].currentSrc; 
anchor.target = '_self'; 
anchor.download = h.split('&name=')[1].replace(/%20/g, ' ') + ' ' + h.substring(h.lastIndexOf("/")+1, h.indexOf('?')); 
document.body.appendChild(anchor); 
anchor.click();
`
The result it is being downloading with video name
![image](https://user-images.githubusercontent.com/19971564/82570004-ae944980-9b89-11ea-9ef8-5b208ea29b7a.png)

And here is nice named file in download folder:
![image](https://user-images.githubusercontent.com/19971564/82570336-1cd90c00-9b8a-11ea-9773-ad797904095c.png)

I may wait for your script to work out and then modify every link with my own script(which would be a crutch), or fork your script and directly make such changes, but I would like to receive your future updates and not mess with your script manually(I even don't propose a pull request, giving all code here). 
I may leave at my side a second script for downloading(as it is better to be a separate script, to not overload users memory with duplicating main script context in every new tab), but it would be grate if you could make such an simple update to your code. All videos would still work as before, but there would be nice potentiality to download videos with human-recognizable name)

**Comment by 684102** [comment]
You can **CTRL+V** whenever clicked on the download button to paste the name of move 
Duplicate of #4

**Comment by NightLancer** [comment]
@684102 Okay... There was no information about such possibility...
I've read #4 and found it a somewhat different request(there was about manual saving, and I was telling about automated one), not I am asking for.

Okay, I've already done 2 simple scripts that resolves my request. One is running 3 seconds after page is loaded(it's enough for download buttons to appear), and another autosaves a video with name and server name(which is also needed in case of quality upgrade case[previous free quality was 720p, now it is 1080p]).

So I don't think it is duplicate, but if you don't want to make such change — than ok. 
Good luck with your work.

**Comment by NightLancer** [comment]
Oh, I didn't notice that your script was not only for pornhub, as I'm not using other sites... With that information in mind, my request really may be seemed too ambitious. Closed.

**Comment by 684102** [comment]
> Oh, I didn't notice that your script was not only for pornhub, as I'm not using other sites... With that information in mind, my request really may be seemed too ambitious. Closed.

The download with name in pornhub seem only work with firefox browser, i've tested on chrome with download in a tag , it not work .

**Comment by 684102** [comment]
Anyway, i will add the download="{name}" on next update.
Thank you.

**Comment by NightLancer** [comment]
> The download with name in pornhub seem only work with firefox browser, i've tested on chrome with download in a tag , it not work .

Yes, I'm using only Firefox, and don't know about all differences with Chrome. Too bad... 

> Anyway, i will add the download="{name}" on next update.
> Thank you.

Ok) Thanks.

**Comment by NightLancer** [comment]
P.S. but it would not be superfluous to add information about "CTRL+V" feature somewhere in description of the script, as not every user goes to github and reads solved issues)

**Comment by 684102** [comment]
> P.S. but it would not be superfluous to add information about "CTRL+V" feature somewhere in description of the script, as not every user goes to github and reads solved issues)

Download with the name is now working on pornhub, xvideos , tube8...
upgrade at http://bit.ly/porndown2
